Fix API 'POST /api/v1/apikeys' wasn't creating new record with the provided ID
At a high level fixes `st2api key load` that wasn't idempotent and failing to import same file twice with:
```
HTTPError: 409 Client Error: Conflict
MESSAGE: Tried to save duplicate unique keys (E11000 duplicate key error collection: st2.api_key_d_b index: key_hash_1 dup key: { : "903b7f0761094265969761443f4f25fc87c780b6248c38ce8dbaadfa52a2b53fd72381ac141072cb53ae78ff02e16fdfc0e40001472b9f25585a7b2864c501db" }) for url: http://127.0.0.1:9101/v1/apikeys
```
because it couldn't import records with the requested ID.