Pin dnspython pip dependency due to regression in v2.0.0
dnspython updated to v2.0.0 results in the following errors:
```
2020-07-19 15:47:56,299 ERROR [-] Failed to connect to database "st2" @ "mongo:27017" as user "None": No servers found yet
```
and
```
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
```