Display friendly message for error in action parameters validation
Display only the human friendly message from the jsonschema validation error. Remove the unicode prefix in the string.

```
~/st2$ st2 run core.local
ERROR: 400 Client Error: Bad Request
MESSAGE: 'cmd' is a required property

~/st2$ st2 run default.ping count=x
ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('count' was unexpected)
```